#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
	pgrep -f speedtest_cn_regular_visit.py > /dev/null
	if [ $? -eq 0 ]; then
		echo "speedtest_cn_regular_visit.py is already running"
		exit 1
	fi
    echo "Starting speedtest_cn_regular_visit.py"
    /root/scripts/speedtest_cn_regular_visit.py >> /tmp/speed-test-cn-regular-visit.log 2>&1 &
}

stop() {
    echo "Stopping speedtest_cn_regular_visit.py"
    kill -9 $(pgrep -f speedtest_cn_regular_visit.py)
}

restart() {
    stop
    sleep 1
    start
}

boot() {
    start
}

shutdown() {
    stop
}

status() {
    pgrep -f speedtest_cn_regular_visit.py > /dev/null
    if [ $? -eq 0 ]; then
        echo "speedtest_cn_regular_visit.py is running"
    else
        echo "speedtest_cn_regular_visit.py is not running"
    fi
}

reload() {
    echo "Reloading configuration..."
    restart
}